import { useState } from "react";
import { reviewCode } from "../api";

export default function CodeEditor() {
  const [code, setCode] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async () => {
    if (!code.trim()) {
      setError("Please enter some code first.");
      return;
    }

    setLoading(true);
    setError("");
    setResult("");

    try {
      const response = await reviewCode(code);
      setResult(response.data.result);
    } catch (err) {
      setError(
        err.response?.data?.error ||
          "Unable to review code."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleClear = () => {
    setCode("");
    setResult("");
    setError("");
  };

  const cleanText = (text) => {
    return text
      .replace(/\*\*/g, "")
      .replace(/```python/g, "")
      .replace(/```/g, "")
      .replace(/^#+\s*/gm, "")
      .trim();
  };

  const getSection = (title, nextTitles = []) => {
    if (!result) return "";

    const escapedTitle = title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

    let pattern = `(?:\\*\\*)?${escapedTitle}(?:\\*\\*)?\\s*\\n?([\\s\\S]*?)`;

    if (nextTitles.length > 0) {
      const nextPattern = nextTitles
        .map(
          (item) =>
            `(?:\\*\\*)?${item.replace(
              /[.*+?^${}()|[\]\\]/g,
              "\\$&"
            )}(?:\\*\\*)?`
        )
        .join("|");

      pattern += `(?=${nextPattern}|$)`;
    } else {
      pattern += "$";
    }

    const match = result.match(
      new RegExp(pattern, "i")
    );

    return match ? cleanText(match[1]) : "";
  };

  const bugs = getSection("Bugs", [
    "Issues",
    "Improvements",
    "Fixed Code",
  ]);

  const issues = getSection("Issues", [
    "Improvements",
    "Fixed Code",
  ]);

  const improvements = getSection("Improvements", [
    "Fixed Code",
  ]);

  const fixedCode = getSection("Fixed Code");

  return (
    <div className="editor-wrapper">

      {/* ================= CODE EDITOR ================= */}

      <div className="review-card">

        <div className="card-header">
          <div>
            <h2>Code Editor</h2>
            <p>
              Paste your code below and let AI analyze it.
            </p>
          </div>

          <span className="language-badge">
            Code
          </span>
        </div>

        <textarea
          className="code-editor"
          value={code}
          onChange={(e) => setCode(e.target.value)}
          placeholder="// Write or paste your code here..."
          spellCheck="false"
        />

        <div className="editor-info">
          <span>
            {code.length} characters
          </span>

          <span>
            {code.split("\n").length} lines
          </span>
        </div>

        {error && (
          <div className="error-message">
            {error}
          </div>
        )}

        <div className="button-area">

          <button
            className="clear-button"
            onClick={handleClear}
            disabled={loading || !code}
          >
            Clear
          </button>

          <button
            className="review-button"
            onClick={handleSubmit}
            disabled={loading}
          >
            {loading
              ? "Reviewing..."
              : "Review Code"}
          </button>

        </div>

      </div>

      {/* ================= LOADING ================= */}

      {loading && (
        <div className="result-card">

          <div className="loading">
            <div className="loading-spinner"></div>

            <div>
              AI is reviewing your code...
            </div>
          </div>

        </div>
      )}

      {/* ================= AI RESULT ================= */}

      {result && !loading && (
        <div className="result-card">

          <div className="card-header">

            <div>
              <h2>AI Code Review</h2>

              <p>
                Analysis generated by your AI reviewer.
              </p>
            </div>

            <span className="language-badge">
              AI Analysis
            </span>

          </div>

          {/* BUGS */}

          {bugs && (
            <div className="review-section bugs-section">

              <div className="review-section-header">

                <div className="review-icon">
                  🐛
                </div>

                <div>
                  <h3>Bugs</h3>
                  <p>
                    Potential runtime errors or bugs
                    found in your code.
                  </p>
                </div>

              </div>

              <pre>{bugs}</pre>

            </div>
          )}

          {/* ISSUES */}

          {issues && (
            <div className="review-section issues-section">

              <div className="review-section-header">

                <div className="review-icon">
                  ⚠️
                </div>

                <div>
                  <h3>Issues</h3>
                  <p>
                    Code quality and implementation
                    issues.
                  </p>
                </div>

              </div>

              <pre>{issues}</pre>

            </div>
          )}

          {/* IMPROVEMENTS */}

          {improvements && (
            <div className="review-section improvements-section">

              <div className="review-section-header">

                <div className="review-icon">
                  💡
                </div>

                <div>
                  <h3>Improvements</h3>
                  <p>
                    Suggestions to make your code
                    cleaner and better.
                  </p>
                </div>

              </div>

              <pre>{improvements}</pre>

            </div>
          )}

          {/* FIXED CODE */}

          {fixedCode && (
            <div className="review-section fixed-code-section">

              <div className="review-section-header">

                <div className="review-icon">
                  ✅
                </div>

                <div>
                  <h3>Fixed Code</h3>
                  <p>
                    Improved version of your code.
                  </p>
                </div>

              </div>

              <pre className="fixed-code">
                {fixedCode}
              </pre>

            </div>
          )}

        </div>
      )}

    </div>
  );
}